services:  
  postgresql:
    env_file: .env
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"

  fastapi: 
    build: .
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_DRIVER_NAME: "postgresql+asyncpg"
      DATABASE_HOST: postgresql

    depends_on:
      - postgresql
